World_books/WebBooks/WebBooks/urls.py
from django.contrib import admin 
from django.urls import path 
from catalog import views 
from django.urls import re_path
 
urlpatterns = [ path('', views.index, name='index'), path('admin/', admin.site.urls),
             re_path(r'^books/$', views.BookListView.as_view(), name='books')] 

World_books/WebBooks/catalog/urls.py
from django.urls import path 
from . import views 
 
urlpatterns = [ 
    path('', views.index, name='index'), 
] 

World_books/WebBooks/catalog/models.py
from django.db import models
from django.urls import reverse 

class Genre(models.Model): 
    name = models.CharField(max_length=200, 
                            help_text=" Введите жанр книги", verbose_name="Жанр книги") 
 
    def __str__(self):         return self.name 

class Language(models.Model): 
    name = models.CharField(max_length=20, 
                            help_text=" Введите язык книги", verbose_name="Язык книги") 
 
    def __str__(self):         return self.name 

class Author(models.Model): 
    first_name = models.CharField(max_length=100, help_text="Введите имя автора", verbose_name="Имя автора") 
    last_name = models.CharField(max_length=100, help_text="Введите фамилию автора", verbose_name="Фамилия автора") 
    date_of_birth = models.DateField(help_text="Введите дату рождения", verbose_name="Дата рождения", 
                                     null=True, blank=True) 
    date_of_death = models.DateField(help_text="Введите дату смерти", verbose_name="Дата смерти", null=True, blank=True) 
 
    def __str__(self): 
        return self.last_name 

class Book(models.Model):     
    title = models.CharField(max_length=200, help_text="Введите название книги", verbose_name="Название книги") 
    genre = models.ForeignKey('Genre', on_delete=models.CASCADE,help_text=" Выберите жанр для книги", verbose_name="Жанр книги", null=True) 
    language = models.ForeignKey('Language',on_delete=models.CASCADE,help_text="Выберите язык книги", 
    verbose_name="Язык книги", null=True)     
    author = models.ManyToManyField('Author', help_text="Выберите автора книги", verbose_name="Автор книги") 
    summary = models.TextField(max_length=1000, help_text="Введите краткое описание книги", verbose_name="Аннотация книги") 
    isbn = models.CharField(max_length=13, help_text="Должно содержать 13 символов", verbose_name="ISBN книги") 
 
    def __str__(self): return self.title 
 
    def get_absolute_url(self): 
        # Возвращает url-адрес для доступа к определенному экземпляру книги.         
        return reverse('book-detail', args=[str(self.id)]) 
    
    def display_author(self): 
     return ', '.join([author.last_name for author in self.author.all()]) 
    display_author.short_description = 'Авторы' 

    
    

class Status(models.Model):     name = models.CharField(max_length=20, 
    help_text="Введите статус экземпляра книги", verbose_name="Статус экземпляра книги") 
 
def __str__(self): return self.name 

class BookInstance(models.Model):     
    book = models.ForeignKey('Book', on_delete=models.CASCADE, null=True) 
    inv_nom = models.CharField(max_length=20, null=True, help_text="Введите инвентарный номер экземпляра", verbose_name="Инвентарный номер") 
    imprint = models.CharField(max_length=200, help_text="Введите издательство и год выпуска", verbose_name="Издательство") 
    status = models.ForeignKey('Status', on_delete=models.CASCADE, null=True, help_text='Изменить состояние экземпляра', verbose_name="Статус экземпляра книги")     
    due_back = models.DateField(null=True, blank=True, help_text="Введите конец срока статуса", verbose_name="Дата окончания статуса") 
 
    def __str__(self): return '%s %s %s' % (self.inv_nom, self.book, self.status) 

World_books/WebBooks/catalog/views.py
from django.shortcuts import render 
from django.http import HttpResponse 
from .models import Book, Author, BookInstance, Genre 

def index(request): 
    # Генерация "количеств" некоторых главных объектов 
    num_books = Book.objects.all().count()     
    num_instances = BookInstance.objects.all().count() 
    # Доступные книги (статус = 'На складе') 
    # Здесь метод 'all()' применен по умолчанию.     
    num_instances_available = BookInstance.objects.filter(status__exact=2).count() 
    # Авторы книг, 
    num_authors = Author.objects.count() 
 
    # Отрисовка HTML-шаблона index.html с данными 
    # внутри переменной context 
    return render(request, 'index.html', context={ 
                                         'num_books': num_books, 
                                         'num_instances': num_instances, 
                                         'num_instances_available': num_instances_available, 
                                         'num_authors': num_authors, 
                                         #'num_visits': num_visits
                                         }) 

from django.views import generic
class BookListView(generic.ListView):
    model = Book

World_books/WebBooks/catalog/templates/base_generic.html
<!DOCTYPE html> 
<html lang="en"> 
<head> 
  {% block title %}<title>Мир книг</title>{% endblock %} 
  <meta charset="utf-8"> 
  <meta name="viewport" content="width=device-width,                         initial-scale=1"> 
  <link rel="stylesheet" 
        href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"> 
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script> 
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script> 
 
  <!-- Добавление статического CSS файла --> 
  {% load static %} 
  <link rel="stylesheet" href="{% static 'css/styles.css' %}"> 
  {% block head %} 
      <img src="{% static 'images/logotip.jpg' %}" style="width:100px; height:100px;"  align="absmiddle"> 
      <font size=7, color="blue">Сайт "Мир книг"</font> 
  {% endblock %} 
</head> 
 
<body> 
  <div class="container-fluid"> 
 
    <div class="row"> 
      <div class="col-sm-2"> 
      {% block sidebar %} 
      <ul class="sidebar-nav"> 
          <li><a href="{% url 'index'%}">Главная страница</a></li> 
          <li><a href="{% url 'books' %}">Все книги</a></li>
          <li><a href="">Все авторы</a></li> 
      </ul> 
      {% endblock %} 
      </div> 
      <div class="col-sm-10 "> 
      {% block content %}{% endblock %} 
      {% block footer %} 
         {% block copyright %} 
       <p>Copyright ООО "Люди и книги", 2020. Все права защищены</p> 
         {% endblock %} 
      {% endblock %} 
 
      </div> 
    </div> 
  </div> 
</body> 
</html> 

World_books/WebBooks/catalog/templates/catalog/Вook_list.html
{% extends "base_generic.html" %} 
 
{% block content %}
    <h1>Список книг в БД</h1> 
    {% if book_list %} 
    <ul> 
    {% for book in book_list %} 
      <li> 
        <a href="{{ book.get_absolute_url }}"> 
                 {{ book.title }}</a> 
                 ({{book.genre}}) 
      </li> 
    {% endfor %} 
    </ul> 
    {% else %}
      <p>В базе данных нет книг</p> 
    {% endif %} 
{% endblock %} 

World_books/WebBooks/catalog/templates/index.html
{% extends "base_generic.html" %} 
 
{% block content %} <h1>Главная страница</h1> 
 
  <p>Добро пожаловать в <em>Мир книг</em>, Это очень простой     веб-сайт, написанный на  Django. Разработан на Python     в качестве учебного примера с использованием PyCharm.</p> 
 
<h2>Динамический контент</h2> 
 
  <p>База данных сайта Мир книг содержит следующее      количество записей :</p>   <ul> 
    <li><strong>Количество книг:</strong> {{ num_books }}</li>     <li><strong>Количество экземпляров книг:         </strong> {{ num_instances }}</li>     <li><strong>Количество экземпляров книг в заказе:         </strong> {{ num_instances_available }}</li>     <li><strong>Количество авторов книг: 
        </strong> {{ num_authors }}</li> 
  </ul> 
{% endblock %} 